theme: jekyll-theme-minimal
title: VetText
description: Repository for VetText veterinary text-mining forum
logo: VetText.png
show_downloads: false

toc: true
toc_label: "Table of contents"
toc_sticky: true
