theme: jekyll-theme-minimal
title: VetText
include: [_pages, _include]
description: Repository for VetText veterinary text-mining forum
logo: 
show_downloads: false
baseurl: /VetText

toc: true
toc_label: "Table of contents"
toc_sticky: true

sidebar:
  title: "Navigation"
  nav: navigation-sidebar
