remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

title: VetText
email: rtnorle@liverpool.ac.uk
description: Veterinary text-mining
# show_downloads: false

baseurl: /VetText
author: PJMNoble

include: 
   - '_pages'
   - '_pages/agendas/*.md'

exclude:
   - Gemfile
   - Gemfile.lock

