# theme: jekyll-theme-minimal
theme: dbyll
title: VetText
description: Veterinary text-mining
baseurl: /VetText
author: pjmnoble

header_pages:
  - _pages/about.md
  - _pages/contacts.md
  - _pages/meetings.md
  
include: 
  - _pages

